version: '3'

services:
  db:
    image: mysql:5.7
    command:
      - --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true

    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-node-mysql

  node:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - nginx-node-mysql
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - nginx-node-mysql
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  nginx-node-mysql:
    driver: bridge